INNER JOIN BOOK_AUTHOR BA ON B.Book_id = BA.Book_id;

SELECT BL.Card_No,
FROM BOOK B

SELECT BL.Date_Out,
FROM BOOK B

SELECT BL.Due_Date
FROM BOOK B

INNER JOIN BOOK_LENDING BL ON B.Book_id = BL.Book_id

INNER JOIN LIBRARY_BRANCH LB ON BL.Branch_id = LB.Branch_id;
