CREATE DATABASE ORDERS;

USE ORDERS;

CREATE TABLE SALESMAN (SALESMAN_ID INT PRIMARY KEY, NAME VARCHAR(20),
CITY VARCHAR(20), COMMISSION VARCHAR(20));
DESC SALESMAN;

CREATE TABLE CUSTOMER( CUSTOMER_ID INT PRIMARY KEY, CUST_NAME VARCHAR(20),
CITY VARCHAR(20), GRADE INT, SALESMAN_ID INT,
FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID) ON DELETE SET NULL);
DESC CUSTOMER;
