CREATE DATABASE ORDERS;

USE ORDERS;

CREATE TABLE SALESMAN (SALESMAN_ID INT PRIMARY KEY, NAME VARCHAR(20),
CITY VARCHAR(20), COMMISSION VARCHAR(20));
DESC SALESMAN;

CREATE TABLE CUSTOMER( CUSTOMER_ID INT PRIMARY KEY, CUST_NAME VARCHAR(20),
CITY VARCHAR(20), GRADE INT, SALESMAN_ID INT,
FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID) ON DELETE SET NULL);
DESC CUSTOMER;

CREATE TABLE ORDERS( ORDER_NO INT PRIMARY KEY, PURCHASE_AMOUNT INT, ORDER_DATE DATE, CUSTOMER_ID INT, SALESMAN_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID) ON DELETE CASCADE);
DESC ORDERS;

INSERT INTO SALESMAN VALUES(1000,"AYUSH","MANGALORE","25%");
INSERT INTO SALESMAN VALUES(1001,"KARTHIK","BANGALORE","30%");
INSERT INTO SALESMAN VALUES(1002,"RIDHAAN","CHENNAI","15%");
INSERT INTO SALESMAN VALUES(1003,"ABHIK","DELHI","10%");
INSERT INTO SALESMAN VALUES(1004,"APOORVA","BANGALORE","5%");
