SELECT GRADE,COUNT(DISTINCT CUSTOMER_ID) FROM CUSTOMER

GROUP BY GRADE HAVING GRADE > (SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY='BANGALORE');

SELECT SALESMAN_ID, NAME FROM SALESMAN S WHERE
(SELECT COUNT(*) FROM CUSTOMER WHERE SALESMAN_ID=S.SALESMAN_ID)>1;


