SELECT GRADE,COUNT(DISTINCT CUSTOMER_ID) FROM CUSTOMER

GROUP BY GRADE HAVING GRADE > (SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY='BANGALORE');

SELECT SALESMAN_ID, NAME FROM SALESMAN S WHERE
(SELECT COUNT(*) FROM CUSTOMER WHERE SALESMAN_ID=S.SALESMAN_ID)>1;

SELECT S.SALESMAN_ID, S.NAME, C.CUST_NAME, S.COMMISSION FROM SALESMAN S, CUSTOMER C WHERE S.CITY=C.CITY AND S.SALESMAN_ID=C.SALESMAN_ID
UNION
SELECT SALESMAN_ID, NAME, 'NO MATCH' ,COMMISSION FROM SALESMAN WHERE NOT CITY = ANY (SELECT CITY FROM CUSTOMER) ORDER BY 2 DESC;

CREATE VIEW HIGH_ORDER_VIEW AS SELECT O.ORDER_DATE, S.SALESMAN_ID, S.NAME
FROM SALESMAN S, ORDERS O WHERE S.SALESMAN_ID=O.SALESMAN_ID AND O.PURCHASE_AMOUNT=(SELECT MAX(PURCHASE_AMOUNT) FROM ORDERS O1 WHERE O1.ORDER_DATE=O.ORDER_DATE);
SELECT * FROM HIGH_ORDER_VIEW;

SELECT * FROM HIGH_ORDER_VIEW;
