SELECT BC.Branch_id,
FROM BOOK B

SELECT BC.No_of_Copies
FROM BOOK B

INNER JOIN BOOK_COPIES BC ON B.Book_id = BC.Book_id;

SELECT LB.Branch_id,
FROM LIBRARY_BRANCH LB

SELECT LB.Branch_Name,
FROM LIBRARY_BRANCH LB

